### ISSUE TITLE
What's `hst`?

### ISSUE THREAD

**Issue by crabdancing** [bendlas/openproject-nix#1]
I couldn't find anything on this, no matter what search engine I tried. What is the `hst` option being set in [`module.nix`](https://github.com/bendlas/openproject-nix/blob/614b4f17d1dc9465468e57640817042354e62d74/module.nix#L84)?

It seems to be unrecognized.

**Comment by bendlas** [comment]
Fixed in https://github.com/bendlas/openproject-nix/commit/0e468799bde68a6b5bd01d5303f87b58407092ee

Thanks for bringing this to my attention. This was a reference to https://host-shell.tech/, from which this module is broken out.

That project isn't yet public, so its wouldn't show up in a search engine. Even if it was, this reference would have been in error, apologies.

**Comment by crabdancing** [comment]
No worries. Thanks for the explanation! :D My fork with the line commented out worked fine, so I was a bit confused. :P
